### ISSUE TITLE
error in running the demo file (unexpected EOF, expected 98300 more bytes. The file might be corrupted)

### ISSUE THREAD

**Issue by 00zahra000** [RenYurui/Neural-Texture-Extraction-Distribution#25]
Hello everyone.
I faced this error when I tried to run demo file (pose control):
I reinstalled the requirements and checked everything. What do you suggest to solve this issue?

net [net_G] parameter count: 42,612,402
net [net_D] parameter count: 26,885,697
Setup trainer.
Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    None)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/util/trainer.py", line 42, in get_trainer
    train_dataset)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/trainers/extraction_distribution_trainer.py", line 21, in __init__
    train_data_loader, val_data_loader)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/trainers/base.py", line 52, in __init__
    self._init_loss(opt)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/trainers/extraction_distribution_trainer.py", line 44, in _init_loss
    weight_style_to_perceptual=getattr(opt.trainer.vgg_param, 'style_to_perceptual', 0)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/loss/perceptual.py", line 34, in __init__
    self.model = _vgg19(layers)
  File "/home/tookai/zahra-h/Projects/Neural-Texture-Extraction-Distribution/loss/perceptual.py", line 164, in _vgg19
    network = torchvision.models.vgg19(pretrained=True).features
  File "/home/tookai/miniconda3/envs/NTED/lib/python3.6/site-packages/torchvision/models/vgg.py", line 172, in vgg19
    return _vgg('vgg19', 'E', False, pretrained, progress, **kwargs)
  File "/home/tookai/miniconda3/envs/NTED/lib/python3.6/site-packages/torchvision/models/vgg.py", line 93, in _vgg
    progress=progress)
  File "/home/tookai/miniconda3/envs/NTED/lib/python3.6/site-packages/torch/hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/tookai/miniconda3/envs/NTED/lib/python3.6/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/tookai/miniconda3/envs/NTED/lib/python3.6/site-packages/torch/serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
**RuntimeError: unexpected EOF, expected 98300 more bytes. The file might be corrupted.`**

**Comment by 00zahra000** [comment]
I solved this issue by downloading the vgg19 weights file manually ( check the colab demo for the link) and hard-coded it in the code.
